### ISSUE TITLE
Your repo is missing a license file

### ISSUE THREAD

**Issue by repomountie** [bcgov/eao-public#77]
Hi there - my investigation found you do not have a license file in your repo, eh. 

DYK: Adding a license to your repo is this easy:
https://help.github.com/articles/adding-a-license-to-a-repository/

Btw, the default license for BCGov GitHub projects is Apache 2.0

**Comment by repomountie** [comment]
Bump.

**Comment by asanchezr** [comment]
@repomountie Great catch! We will update the repo. Thanks!

**Comment by repomountie** [comment]
I'm here to serve and protect.
